"""Scoring modules that turn audited features into model beliefs."""

from quantfore_research.scoring.baseline import (
    ACTION_LABELS,
    BASELINE_MODEL_VERSION,
    RESEARCH_LABEL_BANDS,
    REQUIRED_FEATURE_NAMES,
    BaselineScore,
    ResearchLabelBand,
    ScoreDriver,
    action_label_for_score,
    calculate_baseline_score,
)
from quantfore_research.scoring.ledger import decimal_text, immutable_prediction_hash
from quantfore_research.scoring.multifactor import (
    FAMILY_WEIGHTS,
    MINIMUM_COMPONENT_COVERAGE,
    MINIMUM_FAMILIES,
    MINIMUM_SECTOR_SAMPLE,
    NORMALIZATION_VERSION,
    MULTIFACTOR_HORIZONS,
    MULTIFACTOR_MODEL_VERSION,
    MultiFactorCohortScore,
    NormalizedComponent,
    SecurityMultiFactorScore,
    normalization_input_hash,
    normalize_multifactor_cohort,
    store_multifactor_cohort_scores,
    store_multifactor_predictions,
)
from quantfore_research.scoring.model_v2 import (
    FAMILY_WEIGHTS as MODEL_V2_FAMILY_WEIGHTS,
    MINIMUM_BRANCH_CROSS_SECTION as MODEL_V2_MINIMUM_BRANCH_CROSS_SECTION,
    MODEL_V2_MODEL_VERSION,
    MODEL_V2_NORMALIZATION_VERSION,
    ModelV2CohortScore,
    NormalizedModelV2Component,
    SecurityModelV2Score,
    normalize_model_v2_cohort,
)

__all__ = [
    "ACTION_LABELS",
    "BASELINE_MODEL_VERSION",
    "RESEARCH_LABEL_BANDS",
    "REQUIRED_FEATURE_NAMES",
    "BaselineScore",
    "FAMILY_WEIGHTS",
    "MINIMUM_COMPONENT_COVERAGE",
    "MINIMUM_FAMILIES",
    "MINIMUM_SECTOR_SAMPLE",
    "MODEL_V2_FAMILY_WEIGHTS",
    "MODEL_V2_MINIMUM_BRANCH_CROSS_SECTION",
    "MODEL_V2_MODEL_VERSION",
    "MODEL_V2_NORMALIZATION_VERSION",
    "ModelV2CohortScore",
    "MultiFactorCohortScore",
    "NORMALIZATION_VERSION",
    "MULTIFACTOR_HORIZONS",
    "MULTIFACTOR_MODEL_VERSION",
    "NormalizedComponent",
    "NormalizedModelV2Component",
    "ResearchLabelBand",
    "ScoreDriver",
    "SecurityMultiFactorScore",
    "SecurityModelV2Score",
    "action_label_for_score",
    "calculate_baseline_score",
    "decimal_text",
    "immutable_prediction_hash",
    "normalization_input_hash",
    "normalize_multifactor_cohort",
    "normalize_model_v2_cohort",
    "store_multifactor_cohort_scores",
    "store_multifactor_predictions",
]
